<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Daedalus.Contracts.ModManager\Daedalus.Contracts.ModManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda" Version="0.54.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Embedded\*.json" />
  </ItemGroup>

</Project>
