<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.Versioning.SupportedOSPlatformAttribute">
      <_Parameter1>windows</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ariadne.VFS.WinFsp.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="winfsp.net" Version="2.2.26215" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ariadne.VFS\Ariadne.VFS.csproj" />
  </ItemGroup>

</Project>
